FROM python:3.9-alpine

RUN apk add --update --no-cache --virtual .tmp-build-deps \
    gcc libc-dev linux-headers postgresql-dev \
    && apk add libffi-dev

RUN pip3 install textX
RUN pip3 install py-solc-x

# install git
RUN apk update
RUN apk add git

# install bash
RUN apk add --no-cache bash

# install starship
RUN apk add starship
RUN echo 'eval "$(starship init bash)"' >> ~/.bashrc