FROM python:3.9-alpine

RUN apk add --update --no-cache --virtual .tmp-build-deps \
    gcc libc-dev linux-headers postgresql-dev \
    && apk add libffi-dev

WORKDIR /app
COPY . .

RUN python -m pip install --upgrade pip
RUN pip3 install textX[dev]
RUN pip3 install py-solc-x

RUN pip3 install pygls
RUN pip install --force-reinstall -v "lsprotocol==2022.0.0a10"

RUN pip3 install -e src/spm
RUN pip3 install -e src/spmgen
RUN pip3 install -e src/spl
RUN pip3 install -e src/splgen

# install npm for extension compile
RUN apk add --update npm

# install git
RUN apk update
RUN apk add git

# install bash
RUN apk add --no-cache bash

# install starship
RUN apk add starship
RUN echo 'eval "$(starship init bash)"' >> ~/.bashrc